name: enable test

on:
  push:
    branches: [master]
  workflow_dispatch:   

jobs:
  run_features:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      
      - name: Test
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
         cd BusinessCentralAutomation/Microsoft.Dynamics365.UIAutomation.Enable
         dotnet test --no-build
