using System;
using TechTalk.SpecFlow;
using FluentAssertions;
using System.Security;

using Microsoft.Dynamics365.UIAutomation.Browser;
using Microsoft.Dynamics365.UIAutomation.Api.UCI;
using TechTalk.SpecFlow.Infrastructure;

namespace Microsoft.Dynamics365.UIAutomation.Enable.StepDefinitions
{
    [Binding]
    public class EntityStepDefinitions : BaseStepDefinitions
    {
        private readonly ScenarioContext _scenarioContext;
        private readonly FeatureContext _featureContext;
        private readonly ISpecFlowOutputHelper _specFlowOutputHelper;

        private readonly SecureString _bcemailrecipient = System.Configuration.ConfigurationManager.AppSettings["BC_EmailRecipient"].ToSecureString();

        public EntityStepDefinitions(ScenarioContext scenarioContext, FeatureContext featureContext, ISpecFlowOutputHelper specFlowOutputHelper)
        {
            _scenarioContext = scenarioContext;
            _featureContext = featureContext;
            _specFlowOutputHelper = specFlowOutputHelper;
        }

        [StepDefinition(@"user creates a new .*?")]
        public void WhenUserCreatesANew()
        {
            XrmApp.Entity.BC_New();
        }

        [StepDefinition(@"user triggers autocompletion in section '([^']*)' for field '([^']*)'")]
        public void WhenUserTriggersAutocompletionForField(string sectionName, string fieldName)
        {
            var AutogeneratedValue = XrmApp.Entity.BC_AutocompleteField(sectionName, fieldName);
            _specFlowOutputHelper.WriteLine($"AutogeneratedValue: {AutogeneratedValue}");
            _scenarioContext.Add("AutogeneratedValue", AutogeneratedValue);
        }

        [When(@"user tries to enter in section '([^']*)' into field '([^']*)' value '([^']*)'")]
        [StepDefinition(@"user enters in section '([^']*)' into field '([^']*)' value '([^']*)'")]
        public void WhenUserEntersInSectionIntoRecordFieldValue(string sectionName, string fieldName, string fieldValue)
        {
            XrmApp.Entity.BC_SetField(sectionName, fieldName, fieldValue);
        }

        [Then(@"user enters in section '([^']*)' into field '([^']*)' value from field '([^']*)'")]
        public void ThenUserEntersInSectionIntoFieldValueFromField(string sectionName, string targetFieldName, string sourceFieldName)
        {
            string SourceFieldValue = XrmApp.Entity.BC_GetField(sourceFieldName);
            _specFlowOutputHelper.WriteLine($"SourceFieldValue: {SourceFieldValue}");
            XrmApp.Entity.BC_SetField(sectionName, targetFieldName, SourceFieldValue);
        }


        [When(@"user opens a link from the section '([^']*)' field '([^']*)'")]
        public void WhenUserOpensLinkFromSectionField(string sectionName, string fieldName)
        {
            XrmApp.Entity.BC_ClickLinkInField(sectionName, fieldName);
        }

        [StepDefinition(@"user creates a '[^']*?' line field:")]
        [StepDefinition(@"user creates a '[^']*?' line fields:")]
        public void ThenUserCreatesALine(Table lineFields)
        {
            foreach (var line in lineFields.Rows.Select((Value, Index) => new { Value, Index }))
            {
                foreach (var header in lineFields.Header)
                {
                    XrmApp.Entity.BC_SetLineField(line.Index + 1, header, line.Value[header]);
                }
            }
            XrmApp.ThinkTime(1000); //give BC time to autopopulate fields
        }

        [StepDefinition(@"user creates a new '[^']*?' line:")]
        [StepDefinition(@"user creates a new '[^']*?' lines:")]
        public void ThenUserCreatesANewLine(Table lineFields)
        {
            var ActualNumberOfLines = XrmApp.Entity.BC_GetNumberOfLines();
            foreach (var line in lineFields.Rows.Select((Value, Index) => new { Value, Index }))
            {
                foreach (var header in lineFields.Header)
                {
                    var NewLineIndex = line.Index + 1 + ActualNumberOfLines;
                    XrmApp.Entity.BC_SetLineField(NewLineIndex, header, line.Value[header]);
                }
            }
            XrmApp.ThinkTime(1000); //give BC time to autopopulate fields
        }

        [When(@"user changes a '[^']*?' line '([^']*)' field '([^']*)' value to '([^']*)'")]
        public void ThenUserChangesALineFieldValueTo(int lineNumber, string lineFieldName, string lineFieldValue)
        {
            XrmApp.Entity.BC_SetLineField(lineNumber, lineFieldName, lineFieldValue);
        }

        [When(@"user deletes a line '([^']*)'")]
        [When(@"user tries to delete a line '([^']*)'")]
        public void WhenUserTriesToDeleteALine(int lineNumber)
        {
            XrmApp.Entity.BC_ChooseLineOption(lineNumber, "Delete Line");
            var DialogMessage = XrmApp.Entity.BC_GetDialogMessage();
            _specFlowOutputHelper.WriteLine($"DialogMessage: {DialogMessage}");
            DialogMessage.Should().Contain("Go ahead and delete?");
            XrmApp.Entity.BC_Dialog_ClickButton("Yes");
        }

        [When(@"user selects the '([^']*)' line")]
        public void WhenUserSelectsTheLine(int lineNumber)
        {
            XrmApp.Entity.BC_ChooseLineOption(lineNumber, "Select More");
        }

        [When(@"user selects the '([^']*)' line in '([^']*)'")]
        public void WhenUserSelectsTheLineIn(int lineNumber, string tableName)
        {
            XrmApp.Entity.BC_ChooseLineOption(lineNumber, "Select More", tableName);
        }

        [Then(@"user sees that '[^']*?' line '([^']*)' column '([^']*)' has populated value")]
        public void ThenUserSeesThatLineFieldsHavePopulatedValue(int lineNumber, string columnName)
        {
            string ActualLineFieldValue = XrmApp.Entity.BC_GetLineField(lineNumber, columnName);
            _specFlowOutputHelper.WriteLine($"ActualLineFieldValue: {ActualLineFieldValue}");
            ActualLineFieldValue.Should().NotBeEmpty();
        }

        [Then(@"user sees that '[^']*?' line '([^']*)' column '([^']*)' has a value '([^']*)'")]
        public void ThenUserSeesThatLineColumnHasValue(int lineNumber, string columnName, string expectedLineFieldValue)
        {
            string ActualLineFieldValue = XrmApp.Entity.BC_GetLineField(lineNumber, columnName);
            ActualLineFieldValue.Should().Be(expectedLineFieldValue);
        }

        [Then(@"user sees '[^']*?' line fields:")]
        public void ThenUserSeesThatLineFields(Table lineFields)
        {
            foreach (var line in lineFields.Rows.Select((Value, Index) => new { Value, Index }))
            {
                foreach (var header in lineFields.Header)
                {
                    string ActualLineFieldValue = XrmApp.Entity.BC_GetLineField(line.Index + 1, header);
                    var ExpectedLineFieldValue = line.Value[header];
                    ActualLineFieldValue.Should().Be(ExpectedLineFieldValue);
                }
            }
        }

        [Then(@"user sees exactly '([^']*)' line")]
        [Then(@"user sees exactly '([^']*)' lines")]
        public void ThenUserSeesLines(int expectedNumberOfLines)
        {
            var ActualNumberOfLines = XrmApp.Entity.BC_GetNumberOfLines();
            ActualNumberOfLines.Should().Be(expectedNumberOfLines);
        }

        [Then(@"user sees exactly '([^']*)' line in '([^']*)'")]
        public void ThenUserSeesExactlyLineIn(int expectedNumberOfLines, string tableName)
        {
            var ActualNumberOfLines = XrmApp.Entity.BC_GetNumberOfLines(tableName);
            ActualNumberOfLines.Should().Be(expectedNumberOfLines);
        }

        [Then(@"user sees at least '([^']*)' line in '([^']*)'")]
        public void ThenUserSeesAtLeastLineIn(int expectedMinimumNumberOfLines, string tableName)
        {
            var ActualNumberOfLines = XrmApp.Entity.BC_GetNumberOfLines(tableName);
            _specFlowOutputHelper.WriteLine($"ActualNumberOfLines: {ActualNumberOfLines}");
            ActualNumberOfLines.Should().BeGreaterThanOrEqualTo(expectedMinimumNumberOfLines);
        }

        [StepDefinition(@"user sends approval request")]
        public void WhenUserSendsApprovalRequest()
        {
            XrmApp.Entity.BC_SendApprovalRequest();
        }

        [StepDefinition(@"user sends email to vendor")]
        public void WhenUserSendsEmailToVendor()
        {
            XrmApp.Entity.BC_EmailVendor(_bcemailrecipient);
        }

        [When(@"user copies '([^']*)' document '([^']*)'")]
        public void WhenUserCopiesDocument(string documentType, string documentNo)
        {
            XrmApp.Entity.BC_CopyDocument(documentType, documentNo);
        }

        [When(@"user posts the '[^']*?'")]
        public void WhenUserPostsUsingPosting()
        {
            XrmApp.Entity.BC_Post_UsingPosting();
        }

        [When(@"user posts/prints the '[^']*?'")]
        public void WhenUserPostsUsingPostPrint()
        {
            XrmApp.Entity.BC_Post_UsingPostPrint();
        }

        [When(@"user posts the '[^']*?' with option '([^']*)'")]
        public void WhenUserPostsTheWithOption(string postOption)
        {
            XrmApp.Entity.BC_PostWithOption(postOption);
        }

        [When(@"user opens Ledger Entries")]
        public void WhenUserOpensLedgerEntries()
        {
            XrmApp.Entity.BC_OpenLedgerEntries();
        }

        [Then(@"user sees that in section '([^']*)' field '([^']*)' has a value '([^']*)'")]
        [Then(@"user sees that '[^']*?' in section '([^']*)' field '([^']*)' has a value '([^']*)'")]
        public void ThenUserSeesTheRecordIs(string sectionName, string fieldName, string expectedFieldValue)
        {
            var ActualFieldValue = XrmApp.Entity.BC_GetField(sectionName, fieldName);
            ActualFieldValue.Should().Be(expectedFieldValue);
        }

        [Then(@"user sees that in section '([^']*)' field '([^']*)' does not have a value '([^']*)'")]
        [Then(@"user sees that '[^']*?' in section '([^']*)' field '([^']*)' does not have a value '([^']*)'")]
        public void ThenUserSeesThatInSectionFieldDoesNotHaveAValue(string sectionName, string fieldName, string unwantedFieldValue)
        {
            var ActualFieldValue = XrmApp.Entity.BC_GetField(sectionName, fieldName);
            _specFlowOutputHelper.WriteLine($"ActualFieldValue: {ActualFieldValue}");
            ActualFieldValue.Should().NotBe(unwantedFieldValue);
        }

        [Then(@"user sees that in section '([^']*)' field '([^']*)' has a populated value")]
        public void ThenUserSeesThatInSectionFieldHasAPopulatedValue(string sectionName, string fieldName)
        {
            var ActualFieldValue = XrmApp.Entity.BC_GetField(sectionName, fieldName);
            _specFlowOutputHelper.WriteLine($"ActualFieldValue: {ActualFieldValue}");
            ActualFieldValue.Should().NotBeEmpty();
        }

        [Then(@"user sees message that the '[^']*?' was posted successfully")]
        [Then(@"user sees message that the '[^']*?' were posted successfully")]
        public void ThenUserSeesMessageThatPostedSuccessfully()
        {
            var DialogMessage = XrmApp.Entity.BC_GetDialogMessage();
            _specFlowOutputHelper.WriteLine($"DialogMessage: {DialogMessage}");
            DialogMessage.Should().ContainAny("was posted successfully", "was successfully posted", "were posted successfully", "were successfully posted");
            XrmApp.Entity.BC_Dialog_ClickButton("OK");
        }

        [Then(@"user sees that '[^']*?' was created successfully")]
        public void ThenUserSeesThatEntityWasCreatedSuccessfully()
        {
            var AutogeneratedValue = XrmApp.Entity.Bc_GetEntityNoFromHeader();
            _specFlowOutputHelper.WriteLine($"AutogeneratedValue: {AutogeneratedValue}");
            AutogeneratedValue.Should().NotBeEmpty();
        }

        [Then(@"user sees that column '([^']*)' is empty")]
        public void WhenUserSeesThatColumnIsEmpty(string columnName)
        {
            XrmApp.Entity.BC_CheckColumnEmpty(columnName);
        }

        [Then(@"user sees that column '([^']*)' has the same values as column '([^']*)'")]
        public void ThenUserSeesThatColumnHasTheSameValuesAsColumn(string givenColumn, string columnToCheck)
        {
            XrmApp.Entity.BC_CheckColumnsHaveSameValues(givenColumn, columnToCheck);
        }

        [When(@"user displays related documents '([^']*)'")]
        public void WhenUserNavigatesTo(string documentsOption)
        {
            _scenarioContext.Remove("GridItems");
            XrmApp.Entity.BC_NavigateToDocumentsAndSelect(documentsOption);
        }

        [When(@"user selects function '([^']*)'")]
        public void WhenUserSelectsFunction(string function)
        {
            XrmApp.Entity.BC_SelectOptionFunction(function);
        }

        [When(@"user generate suggested lines")]
        public void WhenUserGenerateSuggestedLines()
        {
            XrmApp.Entity.BC_GenerateSuggestedLines();
        }

        [When(@"user chooses a '([^']*)' of '([^']*)'")]
        [StepDefinition(@"user enters into field '([^']*)' value '([^']*)'")]
        public void WhenUserChoosesAOf(string inputFieldName, string inputFieldValue)
        {
            XrmApp.Entity.BC_SetField(inputFieldName, inputFieldValue);
        }

    }
}
